### ISSUE TITLE
changing of crawler trajectory 

### ISSUE THREAD

**Issue by yamadaTaru** [yoshito-n-students/gazebo_continuous_track#1]
クローラの軌道変更を行う方法について質問です. 
論文中では提案手法を任意形状へ適用する際について書かれていると思うのですが, 具体的にどのようにこのプラグインを使って形状を変えれば良いのでしょうか. 
できればプーリの半径を前後輪で違う値にしたいのですが, 何か良い方法等ありましたら教えていただけると幸いです. 
(質問をする場所や質問方法を間違えていたら申し訳ございません)

I have a question about how to change the trajectory of a crawler.
In the paper, I think it describes how to apply the proposed method to an arbitrary geometry, but how exactly should we use this plug-in to change the geometry?
If possible, I would like to change the radius of the pulley to different values for the front and rear wheels.
(I apologize if this is the wrong place or the wrong way to ask this question.)

**Comment by yoshito-okada** [comment]
See the example model files below. These files define the blue track model in the video.
https://github.com/yoshito-n-students/gazebo_continuous_track_example/blob/master/urdf_xacro/example_track.urdf.xacro
https://github.com/yoshito-n-students/gazebo_continuous_track_example/blob/master/urdf_xacro/example_track_gazebo.urdf.xacro
https://www.youtube.com/watch?v=0bPqNbOKPuQ

You can ask questions here but try to do it in English so that the discussion can help non-Japanese people. You can write Japanese and (maybe translated) English side by side.

**Comment by yamadaTaru** [comment]
Thank you for your response.
I have checked the model. 
However, the macro used in the model is for the oval track (it says so in the comments in the code, and the idler radius is not an argument). 
I have tried to implement Sub-track in the last few days, but it seems not possible with the existing macros.
Is it necessary to create a new macro if the radius is different for the front and rear wheels, as in sub-track?
If so, should we create a xaco file (or a new C++ file)?
Sorry for the bad question. 

If possible, I would appreciate it if you could provide an example of the use of different radii for front and back tracks, such as sub-tracks.
Or, if you have a concrete procedure to implement Sub-track instead of an example, it would be appreciated. 
I apologize for the rudeness of this question, but I would appreciate your answer. 
(I accidentally closed the issue but the problem is still there. Sorry.)

**Comment by yamadaTaru** [comment]
> 以下のモデル ファイルの例を参照してください。これらのファイルは、ビデオの青いトラック モデルを定義します。 [https://github.com/yoshito-n-students/gazebo_continuous_track_example/blob/master/urdf_xacro/example_track.urdf.xacro ](https://github.com/yoshito-n-students/gazebo_continuous_track_example/blob/master/urdf_xacro/example_track.urdf.xacro) [https://github.com/yoshito-n-students/gazebo_continuous_track_example/blob/master/urdf_xacro/example_track_gazebo .urdf.xacro ](https://github.com/yoshito-n-students/gazebo_continuous_track_example/blob/master/urdf_xacro/example_track_gazebo.urdf.xacro) https://www.youtube.com/watch?v=0bPqNbOKPuQ
> 
> ここで質問することもできますが、英語で行うようにしてください。ディスカッションが外国人の助けになるからです。日本語と（おそらく翻訳された）英語を並べて書くことができます。

**Comment by yoshito-okada** [comment]
I got your point. Unfortunately, there is no example or helper macros for a track with different front and rear radii.

However, the plugin already supports such kinds of tracks. You have to define a new model via your own .urdf.xacro file. The new model would have an unsymmetrical trajectory as I introduced in Fig. 4 (b) in the paper.

For further questions, you may email me using the address I wrote in the paper. Depending on your objective and its suitability for the plugin, I may be able to help you.

**Comment by yamadaTaru** [comment]
I appreciate your answer. 
Just knowing that I need to create a new .urdf.xacro file helped me.
If I have any problems creating a new file, I may send you an email.

Thank you very much for your time.
